Let's import the NumPy library

In [ ]:
import numpy as np

Broadcasting allows you to perform element-wise operations without the need for explicit looping

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
lst = [1, 2, 3, 4, 5]
lst

[1, 2, 3, 4, 5]

In [ ]:
arr + 10

array([11, 12, 13, 14, 15])

In [ ]:
# lst + 10

In [ ]:
[x + 10 for x in lst]

[11, 12, 13, 14, 15]

In [ ]:
arr ** 3

array([  1,   8,  27,  64, 125])

In [ ]:
# lst ** 3

In [ ]:
[x ** 3 for x in lst]

[1, 8, 27, 64, 125]

Imagine you have the following data which you want to feed into a machine learning algorithm

In [ ]:
data = np.array([
    [25, 50000, 4.5, 1, 0],
    [45, 80000, 12.2, 0, 1],
    [35, 60000, 5, 1, 1]
])
data

array([[2.50e+01, 5.00e+04, 4.50e+00, 1.00e+00, 0.00e+00],
       [4.50e+01, 8.00e+04, 1.22e+01, 0.00e+00, 1.00e+00],
       [3.50e+01, 6.00e+04, 5.00e+00, 1.00e+00, 1.00e+00]])

The data contains the age, income, years of service, gender, and whether the person owns a house or not. However, your machine learning algorithm works best when numeric features are scaled to the range $[-1, 1]$.

We want to scale the age, income, and the years of service, but not the gender or house ownership. We will standardise the columns to scale, i.e., subtract the mean and divide by the standard deviation.

In [ ]:
# Scaling just the first three elements in each row
data[:, :3] = (data[:, :3] - data[:, :3].mean()) / data[:, :3].std()  # standardising by dividing by the standard deviation
data

array([[-0.68725673,  0.94048486, -0.68792444,  1.        ,  0.        ],
       [-0.68660531,  1.91761838, -0.68767364,  0.        ,  1.        ],
       [-0.68693102,  1.26619603, -0.68790815,  1.        ,  1.        ]])

Broadcasting also allows you to perform operations between arrays of different shapes, as long as they follow NumPy's broadcasting rules

In [ ]:
mat = np.array([[10, 20, 30], [40, 50, 60]])
mat

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [ ]:
mat + arr

array([[11, 22, 33],
       [41, 52, 63]])

In [ ]:
# mat + np.array([1, 2])

Imagine we have an array containing the age, income, and credit score of our customers on each row. In our risk-of-default calculations, we want to emphasise the credit score as most important. Thus, we will give it a higher weight.

In [ ]:
features = np.array([[23, 40000, 650], [32, 45000, 700], [40, 80000, 750]])  # age, income, credit score for each customer
features

array([[   23, 40000,   650],
       [   32, 45000,   700],
       [   40, 80000,   750]])

In [ ]:
weights = np.array([1, 1, 3])  # higher weightage to the third feature
weights

array([1, 1, 3])

In [ ]:
features * weights  # multiplying the features matrix by the weights array to get the weighted features matrix

array([[   23, 40000,  1950],
       [   32, 45000,  2100],
       [   40, 80000,  2250]])

Doing the same with lists is a little more complicated

In [ ]:
mat_lst = [[10, 20, 30], [40, 50, 60]]
mat_lst

[[10, 20, 30], [40, 50, 60]]

In [ ]:
arr_lst = [1, 2, 3]
arr_lst

[1, 2, 3]

In [ ]:
mat_lst + arr_lst

[[10, 20, 30], [40, 50, 60], 1, 2, 3]

In [ ]:
[[mat_lst[i][j] + arr_lst[j] for j in range(len(arr_lst))] for i in range(len(mat_lst))]

[[11, 22, 33], [41, 52, 63]]

In [ ]:
features_lst = [[23, 40000, 650], [32, 45000, 700], [40, 80000, 750]]

In [ ]:
weights_lst = [1, 1, 3]

In [ ]:
# features_lst * weights_lst

In [ ]:
[[features_lst[i][j] * weights_lst[j] for j in range(len(weights_lst))] for i in range(len(features_lst))]

[[23, 40000, 1950], [32, 45000, 2100], [40, 80000, 2250]]

Let's compare how broadcasting fares versus list comprehensions by using large arrays and timing them with Python's time library

In [ ]:
big_mat_lst = [[i for i in range(j-1000, j)] for j in range(1000, 11000)]
big_arr_lst = [i for i in range(1000)]

In [ ]:
len(big_mat_lst)

10000

In [ ]:
len(big_mat_lst[0])

1000

In [ ]:
len(big_arr_lst)

1000

In [ ]:
big_mat = np.array(big_mat_lst)
big_arr = np.array(big_arr_lst)

In [ ]:
import time

start_time = time.time()
product = [[big_mat_lst[i][j] * big_arr_lst[j] for j in range(len(big_arr_lst))] for i in range(len(big_mat_lst))]
print('Time taken to multiply a matrix by a list using list comprehension:', time.time() - start_time)

start_time = time.time()
product = big_mat * big_arr
print('Time taken to multiply a matrix by a list using broadcasting:', time.time() - start_time)

Time taken to multiple a matrix by a list using list comprehension: 2.5946125984191895
Time taken to multiple a matrix by a list using broadcasting: 0.14714312553405762


As the size of the arrays increases, broadcasting tends to be much faster than using list comprehensions