Let's import the NumPy library

In [22]:
import numpy as np

In [23]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

We can index and slice NumPy arrays like we can strings, lists, and tuples

In [24]:
my_array[0]

1

In [25]:
my_array[4]

5

In [26]:
my_array[-1]

5

In [27]:
my_array[4:]

array([5])

In [28]:
my_array[:2]

array([1, 2])

In [29]:
my_array[::2]

array([1, 3, 5])

In [30]:
my_array[::-1]

array([5, 4, 3, 2, 1])

We can use boolean indexing to retrieve only those values we mark as `True`. We can mark values in this way by using conditions.

In [31]:
ages_list = [18, 15, 23, 14, 20]

In [32]:
# ages_list >= 18  # cannot compare lists to integers

In [33]:
ages = np.array(ages_list)

In [34]:
ages >= 18

array([ True, False,  True, False,  True])

In [35]:
ages[ages >= 18]

array([18, 23, 20])

In [36]:
ages[[True, False, True, False, True]]

array([18, 23, 20])

In [37]:
# ages[[True, False]]

We can use 'fancy indexing' to select only certain items by index from a NumPy array

In [38]:
my_array[[4, 0, 1]]

array([5, 1, 2])

In [39]:
my_array[[4, 0, 0, 0]]

array([5, 1, 1, 1])

In [40]:
ages[[4, 0, 1]]

array([20, 18, 15])

We can use `np.where()` to get the indices where the elements within a NumPy array meet a condition

In [41]:
indices = np.where(my_array % 2 == 0)
indices

(array([1, 3]),)

In [42]:
my_array[indices]

array([2, 4])

In [64]:
np.where(ages % 2 == 0)

(array([0, 3, 4]),)

We can use `np.where()` to modify NumPy arrays

In [43]:
np.where(my_array > 2, 100, my_array)  # (condition, case if met, else); does not act in place

array([  1,   2, 100, 100, 100])

In [44]:
my_array

array([1, 2, 3, 4, 5])

In [45]:
new_array = np.where(my_array < 4, my_array ** 2, -55)
new_array

array([  1,   4,   9, -55, -55])

We can also directly modify NumPy arrays using subscripts

In [46]:
my_array_2 = my_array  # making a deep copy of my_array
my_array_2

array([1, 2, 3, 4, 5])

In [47]:
my_array_2[my_array_2 > 2] = 100
my_array_2

array([  1,   2, 100, 100, 100])

In [48]:
my_array  # my_array_2 is a deep copy, therefore my_array was also modified

array([  1,   2, 100, 100, 100])

In [49]:
my_array = np.array([1, 2, 3, 4, 5])  # restoring my_array to its initial values

In [50]:
my_array_3 = my_array.copy()  # make a shallow copy
my_array_3

array([1, 2, 3, 4, 5])

In [51]:
my_array_3[my_array_3 > 2] = 100
my_array_3

array([  1,   2, 100, 100, 100])

In [52]:
my_array  # my_array_3 is a shallow copy, therefore my_array was also modified

array([1, 2, 3, 4, 5])

We can slice multidimensional arrays by using commas in subscripts

In [53]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
matrix[1][2]

6

In [55]:
matrix[1, 2]

6

In [56]:
matrix[:3, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [57]:
matrix[2, 1:]

array([8, 9])

In [58]:
matrix[matrix > 2]  # collapses the dimension

array([3, 4, 5, 6, 7, 8, 9])

In [59]:
three_tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
three_tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [60]:
three_tensor[1][1][2]

12

In [61]:
three_tensor[1, 1, 2]

12

In [62]:
three_tensor[1:, :, 2]

array([[ 9, 12],
       [15, 18]])

In [63]:
three_tensor[three_tensor < 12]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])