Let's import the NumPy library

In [ ]:
import numpy as np

Let's find the dot product (scalar product) of two NumPy arrays

In [ ]:
lst_arr1 = [1, 2, 3]
arr1 = np.array(lst_arr1)
lst_arr2 = [4, 5, 6]
arr2 = np.array(lst_arr2)

In [ ]:
dot_product = 0
for i in range(len(lst_arr1)): dot_product += lst_arr1[i] * lst_arr2[i]

dot_product

32

In [ ]:
np.dot(arr1, arr2)

32

How do these two ways of calculating the dot product differ in performance? Let's test this out with large arrays and the `time` library.

In [ ]:
lst_large_arr1 = list(range(1, 100000))
lst_large_arr2 = list(range(1, 100000))

large_arr1 = np.array(lst_large_arr1)
large_arr2 = np.array(lst_large_arr2)

In [ ]:
import time

start_time = time.time()
dot_product = 0
for i in range(len(lst_large_arr1)):
    dot_product += lst_large_arr1[i] * lst_large_arr2[i]

print('Time taken to calculate the dot product for two large arrays using a loop:', time.time() - start_time)

start_time = time.time()
np.dot(large_arr1, large_arr2)
print('Time taken to calculate the dot product for two large arrays using NumPy:', time.time() - start_time)

Time taken to calculate the dot product for two large arrays using a loop: 0.07953286170959473
Time taken to calculate the dot product for two large arrays using NumPy: 0.0005199909210205078


We can perform matrix multiplication on two NumPy arrays

In [ ]:
lst_mat1 = [[1, 2], [3, 4], [5, 6]]
mat1 = np.array(lst_mat1)
lst_mat2 = [[7, 8, 9], [10, 11, 12]]
mat2 = np.array(lst_mat2)

In [ ]:
np.dot(mat1, mat2)  # for 2D arrays, np.dot() performs matrix multiplication

array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])

In [ ]:
mat1 @ mat2

array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])

In [ ]:
np.matmul(mat1, mat2)

array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])

We can find the sum of the elements within a NumPy array

In [ ]:
arr1

array([1, 2, 3])

In [ ]:
arr1.sum()

6

In [ ]:
mat1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
mat1.sum()

21

In [ ]:
mat1.sum(axis = 0)  # get sums of each column

array([ 9, 12])

In [ ]:
mat1.sum(axis = 1)  # get sums of each row

array([ 3,  7, 11])

We can finding the maximum and minimum of a NumPy array

In [ ]:
arr1

array([1, 2, 3])

In [ ]:
arr1.max()

3

In [ ]:
arr1.min()

1

In [ ]:
mat1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
mat1.max()

6

In [ ]:
mat1.max(axis = 0)

array([5, 6])

In [ ]:
mat1.max(axis = 1)

array([2, 4, 6])

In [ ]:
mat1.min()

1

In [ ]:
mat1.min(axis = 0)

array([1, 2])

In [ ]:
mat1.min(axis = 1)

array([1, 3, 5])

We can find the mean of a NumPy array

In [ ]:
arr1

array([1, 2, 3])

In [ ]:
arr1.mean()

2.0

In [ ]:
mat1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
mat1.mean()

3.5

In [ ]:
mat1.mean(axis = 0)

array([3., 4.])

In [ ]:
mat1.mean(axis = 1)

array([1.5, 3.5, 5.5])

We can find the absolute values of elements in a NumPy array

In [ ]:
arr3 = np.array([1, -2, -4, 8])
arr3

array([ 1, -2, -4,  8])

In [ ]:
np.abs(arr3)

array([1, 2, 4, 8])

We can find the exponents of the elements of a NumPy array

In [ ]:
np.exp(arr3)  # calculate e^x for every element

array([2.71828183e+00, 1.35335283e-01, 1.83156389e-02, 2.98095799e+03])

In [ ]:
np.power(arr3, 2)  # calculate squares of every element

array([ 1,  4, 16, 64])

We can find the square roots of the elements of a NumPy array

In [ ]:
arr2

array([4, 5, 6])

In [ ]:
np.sqrt(arr2)

array([2.        , 2.23606798, 2.44948974])

In [ ]:
np.power(arr2, 0.5)

array([2.        , 2.23606798, 2.44948974])

We can sort a NumPy array in ascending or descending order

In [ ]:
arr3

array([ 1, -2, -4,  8])

In [ ]:
np.sort(arr3)

array([-4, -2,  1,  8])

In [ ]:
# np.sort(arr3, reverse = True)

In [ ]:
np.sort(arr3, ascending = False)

In [ ]:
np.sort(arr3)[::-1]

array([ 8,  1, -2, -4])

We can retrieve the indices of a NumPy array which would be the order of the elements were the array sorted

In [ ]:
arr3

array([ 1, -2, -4,  8])

In [ ]:
arr3.argsort()

array([2, 1, 0, 3])